# Generated by Django 4.2.5 on 2023-10-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('processed_clips', models.JSONField(default=list)),
                ('final_video', models.FileField(blank=True, null=True, upload_to='final_videos/')),
                ('transcription', models.TextField(blank=True, null=True)),
                ('uploaded_chunks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
